
import photo from "./image-main/bestseller-img/Rectangle 14 (1).png";
import photo2 from "./image-main/bestseller-img/Rectangle 14.png";
import imgLikes from "./image-main/bestseller-img/like.svg"

 let data = [
    {
        id: 1,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 70+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 24990,
        mirror: true,
    },
    {
        id: 2,
        img:photo2,
        likeImg:imgLikes,
        category: "консоли",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 70+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 24990,
        mirror: true,
    },
    {
        id: 3,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 80+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 4990,
        mirror: true,
    },
    {
        id: 4,
        img:photo2,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Тумбы",
        material:"Lux лдсп",
        size: 80+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 24930,
        mirror: true,
    },
    {
        id: 5,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 100+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 2499,
        mirror: true,
    },
    {
        id: 6,
        img:photo2,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 100+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 24990,
        mirror: true,
    },
    {
        id: 7,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Банкетки",
        material:"Lux лдсп",
        size: 100+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 2490,
        mirror: false,
    },
    {
        id: 8,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 120+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 2490,
        mirror: false,
    },
    {
        id: 9,
        img:photo2,
        likeImg:imgLikes,
        category: "консоли",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 120+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 29190,
        mirror: false,
    },
    {
        id: 10,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 120+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 24290,
        mirror: false,
    },
    {
        id: 11,
        img:photo2,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Тумбы",
        material:"Lux лдсп",
        size: 125+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 24990,
        mirror: false,
    },
    {
        id: 12,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 125+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 990,
        mirror: false,
    },
    {
        id: 13,
        img:photo2,
        likeImg:imgLikes,
        category: "Подвесные тумбы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        size: 125+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 24990,
        mirror: false,
    },
    {
        id: 14,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Банкетки",
        material:"Lux лдсп",
        size: 125+' см',
        likes: 128,
        price:"24 990",
        priceNumber: 24990,
        mirror: false,
    }
]

export default data