import photo from "./image-main/bestseller-img/Rectangle 14 (1).png";
import photo2 from "./image-main/bestseller-img/Rectangle 14.png";
import imgLikes from "./image-main/bestseller-img/like.svg";
import aboutImage1 from "./image-main/aboutProduct/horizondImage.png";
import aboutImage2 from "./image-main/aboutProduct/verticalImage1.png";
import aboutImage3 from "./image-main/aboutProduct/verticalImage2.png";
import reviews1 from "../productPageFolder/imagePageProduct/168002784718767307 1.png"
import reviews2 from "../productPageFolder/imagePageProduct/c970ab26ee_upload_2024_09_03_16_23_51_383 1.png"
import reviews3 from "../productPageFolder/imagePageProduct/task-text 1.png"

let data = [
  {
    id: 1,
    img: photo,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик "7 ящиков серый кашемир " `,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 70 + " см",
    likes: 133,
    price: "24 990",
    priceNumber: 24990,
    mirror: true,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
      { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
    reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 2,
    img: photo2,
    likeImg: imgLikes,
    category: "консоли",
    title: `Туалетный столик, 2в1 GOLD(тумба слева) с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 70 + " см",
    likes: 132,
    price: "24 990",
    priceNumber: 24990,
    mirror: true,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
    { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 3,
    img: photo,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик, 2в1 GOLD (тумба слева) с зеркалом с рамами`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 80 + " см",
    likes: 131,
    price: "4 990",
    priceNumber: 4990,
    mirror: true,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
     { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
    reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 4,
    img: photo2,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик, 2в1 GOLD (тумба слева) с зеркалом с рамами`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 80 + " см",
    likes: 129,
    price: "24 930",
    priceNumber: 24930,
    mirror: true,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
      { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 5,
    img: photo,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик "7 ящиков серый кашемир " с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 100 + " см",
    likes: 128,
    price: "2 499",
    priceNumber: 2499,
    mirror: true,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
     { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 6,
    img: photo2,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик "7 ящиков серый кашемир " с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 100 + " см",
    likes: 127,
    price: "24 990",
    priceNumber: 24990,
    mirror: true,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
      { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 7,
    img: photo,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик "7 ящиков серый кашемир " с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 100 + " см",
    likes: 126,
    price: "2 490",
    priceNumber: 2490,
    mirror: false,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
      { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 8,
    img: photo,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик "7 ящиков серый кашемир " с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 120 + " см",
    likes: 125,
    price: "2 490",
    priceNumber: 2490,
    mirror: false,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
     { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 9,
    img: photo2,
    likeImg: imgLikes,
    category: "консоли",
    title: `Туалетный столик "7 ящиков серый кашемир " с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 120 + " см",
    likes: 124,
    price: "29 190",
    priceNumber: 29190,
    mirror: false,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
     { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 10,
    img: photo,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик "7 ящиков серый кашемир " с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 120 + " см",
    likes: 123,
    price: "24 290",
    priceNumber: 24290,
    mirror: false,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
     { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 11,
    img: photo2,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик "7 ящиков серый кашемир " с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 125 + " см",
    likes: 122,
    price: "24 990",
    priceNumber: 24990,
    mirror: false,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
      { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 12,
    img: photo,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик "7 ящиков серый кашемир " с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 125 + " см",
    likes: 121,
    price: "990",
    priceNumber: 990,
    mirror: false,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
      { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 13,
    img: photo2,
    likeImg: imgLikes,
    category: "Подвесные тумбы",
    title: `Туалетный столик "7 ящиков серый кашемир " с LED зеркалом`,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 125 + " см",
    likes: 120,
    price: "24 990",
    priceNumber: 24990,
    mirror: false,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
      { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
  {
    id: 14,
    img: photo,
    likeImg: imgLikes,
    category: "гримёрные столы",
    title: `Туалетный столик "7 ящиков серый кашемир " `,
    material: "Lux лдсп",
    color: [{ красный: "red", белый: "white", зеленый: "green" }],
    imageForCard: [photo, photo, photo, photo, photo],
    size: 125 + " см",
    likes: 134,
    price: "24 990",
    priceNumber: 24990,
    mirror: false,
    title1: "Заголовок 1",
    discription1:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    subTitle1: "Подзаголовок 1 ",
    discription2:
      "At vitae, ut vitae vestibulum nunc, viverra enim. Eget ullamcorper bibendum lacus nunc, urna, in suscipit. Sed volutpat enim tincidunt a imperdiet fames. Viverra sed neque turpis mi. Odio id rhoncus risus elementum commodo ut.",
    aboutImages: [aboutImage1, aboutImage2, aboutImage3],
    characteristics: [
      { label: "Стол: ", value: "100д х 80в х 40г" },
      { label: "Проем для ног: ", value: "45см" },
      { label: "Гримерное зеркало: ", value: "100д х 80в" },
      { label: "Общая высота стола с зеркалом: ", value: "160см" },
      { label: "Лампы или лэд подсветка: ", value: "4000к-дневной свет" },
      { label: "Стеклянная поверхность: ", value: "1500руб" },
      { label: "Разделители в ящик съемные: ", value: "1000руб" },
      { label: "Розетка: ", value: "500" },
      { label: "Выключатель", value: "" },
      {
        label:
          "Толкатели-открывается и закрывается при помощи нажатия на фасад ящика ариковая система полного выдвижения ящиков.Качественная профессиональная сборка ",
      },
      {
        label: "Отдельно можно добавить: ",
        value: "Банкетка(расцветки разные в наличии)",
      },
      { label: "Размер: ", value: "40д х 40ш х 47в " },
     { labelPrice: "Цена: ", curPrice: "8000руб", newPrice: "2990руб" },
    ],
        reviews: [
reviews1,
reviews2,
reviews3,
reviews1,
reviews2,
reviews3,
    ],
  },
];

export default data;
