
import photo from "./image-main/bestseller-img/Rectangle 14 (1).png";
import photo2 from "./image-main/bestseller-img/Rectangle 14.png";
import imgLikes from "./image-main/bestseller-img/like.svg"

 let data = [
    {
        id: 1,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 70+' см',
        likes: 133,
        price:"24 990",
        priceNumber: 24990,
        mirror: true,
    },
    {
        id: 2,
        img:photo2,
        likeImg:imgLikes,
        category: "консоли",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 70+' см',
        likes: 132,
        price:"24 990",
        priceNumber: 24990,
        mirror: true,
    },
    {
        id: 3,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 80+' см',
        likes: 131,
        price:"4 990",
        priceNumber: 4990,
        mirror: true,
    },
    {
        id: 4,
        img:photo2,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Тумбы",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 80+' см',
        likes: 129,
        price:"24 930",
        priceNumber: 24930,
        mirror: true,
    },
    {
        id: 5,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 100+' см',
        likes: 128,
        price:"2 499",
        priceNumber: 2499,
        mirror: true,
    },
    {
        id: 6,
        img:photo2,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 100+' см',
        likes: 127,
        price:"24 990",
        priceNumber: 24990,
        mirror: true,
    },
    {
        id: 7,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Банкетки",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 100+' см',
        likes: 126,
        price:"2 490",
        priceNumber: 2490,
        mirror: false,
    },
    {
        id: 8,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 120+' см',
        likes: 125,
        price:"2 490",
        priceNumber: 2490,
        mirror: false,
    },
    {
        id: 9,
        img:photo2,
        likeImg:imgLikes,
        category: "консоли",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 120+' см',
        likes: 124,
        price:"29 190",
        priceNumber: 29190,
        mirror: false,
    },
    {
        id: 10,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 120+' см',
        likes: 123,
        price:"24 290",
        priceNumber: 24290,
        mirror: false,
    },
    {
        id: 11,
        img:photo2,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Тумбы",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 125+' см',
        likes: 122,
        price:"24 990",
        priceNumber: 24990,
        mirror: false,
    },
    {
        id: 12,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 125+' см',
        likes: 121,
        price:"990",
        priceNumber: 990,
        mirror: false,
    },
    {
        id: 13,
        img:photo2,
        likeImg:imgLikes,
        category: "Подвесные тумбы",
        title:"Идеальный мини",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 125+' см',
        likes: 120,
        price:"24 990",
        priceNumber: 24990,
        mirror: false,
    },
    {
        id: 14,
        img:photo,
        likeImg:imgLikes,
        category: "гримёрные столы",
        title:"Банкетки",
        material:"Lux лдсп",
        color: [{ "красный": "red", "белый": "white", "зеленый": "green" },],
        size: 125+' см',
        likes: 134,
        price:"24 990",
        priceNumber: 24990,
        mirror: false,
    }
]

export default data